### ISSUE TITLE
installation issues?

### ISSUE THREAD

**Issue by nell-byler** [dfm/python-fsps#48]
I am currently unable to install / run fsps on my laptop. I can't tell if this is the result of an accidental/forced upgrade to Mavericks or upgrading to the new numpy 1.10, because I did them both within a few days of each other and didn't notice anything until I tried to do a re-install python-fsps with the setup.py script.

I'm using homebrew-installed python 2.7.10_2 and gcc/gfortran. I have done a complete clean install of my /usr/local/ directory with homebrew, which included a reinstall of python, python modules, and gcc/gfortran. FSPS compiles and runs just fine!

I've tried installing python-fsps with numpy 1.10 and 1.8., both return errors with installation, but at different places (I tested 1.9 numpy as well, but apparently.this had an issue with f2py that put the wrong shebang at the head of the executable f2py script https://github.com/numpy/numpy/issues/5812).

Here is the output from the command "python setup.py install" with numpy 1.10.1:

running install
running bdist_egg
running egg_info
writing fsps.egg-info/PKG-INFO
writing top-level names to fsps.egg-info/top_level.txt
writing dependency_links to fsps.egg-info/dependency_links.txt
reading manifest file 'fsps.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'fsps.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.11-x86_64/egg
running install_lib
running build_py
running build_ext
Running f2py on ['fsps.f90'] with flags ['-m', '_fsps', '-h', 'fsps.pyf', '--overwrite-signature']
Reading fortran codes...
    Reading file 'fsps.f90' (format:free)
rmbadname1: Replacing "const" with "const_bn".
rmbadname1: Replacing "const" with "const_bn".
Post-processing...
    Block: _fsps
            Block: driver
In: :_fsps:fsps.f90:driver
get_useparameters: no module sps_utils info used by driver
In: :_fsps:fsps.f90:driver
get_useparameters: no module sps_vars info used by driver
In: :_fsps:fsps.f90:driver
    getarrlen:variable "ntfull" undefined
In: :_fsps:fsps.f90:driver
    getarrlen:variable "nz" undefined
In: :_fsps:fsps.f90:driver
    getarrlen:variable "nz" undefined
In: :_fsps:fsps.f90:driver
    getarrlen:variable "nt" undefined
                Block: setup
In: :_fsps:fsps.f90:driver:setup
get_useparameters: no module sps_utils info used by setup
In: :_fsps:fsps.f90:driver:setup
get_useparameters: no module sps_vars info used by setup
                Block: set_ssp_params
In: :_fsps:fsps.f90:driver:set_ssp_params
get_useparameters: no module sps_utils info used by set_ssp_params
In: :_fsps:fsps.f90:driver:set_ssp_params
get_useparameters: no module sps_vars info used by set_ssp_params
                Block: set_csp_params
In: :_fsps:fsps.f90:driver:set_csp_params
get_useparameters: no module sps_utils info used by set_csp_params
In: :_fsps:fsps.f90:driver:set_csp_params
get_useparameters: no module sps_vars info used by set_csp_params
                Block: ssps
In: :_fsps:fsps.f90:driver:ssps
get_useparameters: no module sps_utils info used by ssps
In: :_fsps:fsps.f90:driver:ssps
get_useparameters: no module sps_vars info used by ssps
                Block: ssp
In: :_fsps:fsps.f90:driver:ssp
get_useparameters: no module sps_utils info used by ssp
In: :_fsps:fsps.f90:driver:ssp
get_useparameters: no module sps_vars info used by ssp
                Block: get_ssp_spec
In: :_fsps:fsps.f90:driver:get_ssp_spec
get_useparameters: no module sps_utils info used by get_ssp_spec
In: :_fsps:fsps.f90:driver:get_ssp_spec
get_useparameters: no module sps_vars info used by get_ssp_spec
                Block: interp_ssp
In: :_fsps:fsps.f90:driver:interp_ssp
get_useparameters: no module sps_utils info used by interp_ssp
In: :_fsps:fsps.f90:driver:interp_ssp
get_useparameters: no module sps_vars info used by interp_ssp
In: :_fsps:fsps.f90:driver:interp_ssp
    getarrlen:variable "nt" undefined
                Block: smooth_spectrum
In: :_fsps:fsps.f90:driver:smooth_spectrum
get_useparameters: no module sps_utils info used by smooth_spectrum
In: :_fsps:fsps.f90:driver:smooth_spectrum
get_useparameters: no module sps_vars info used by smooth_spectrum
                Block: compute
In: :_fsps:fsps.f90:driver:compute
get_useparameters: no module sps_utils info used by compute
In: :_fsps:fsps.f90:driver:compute
get_useparameters: no module sps_vars info used by compute
                Block: compute_zdep
In: :_fsps:fsps.f90:driver:compute_zdep
get_useparameters: no module sps_utils info used by compute_zdep
In: :_fsps:fsps.f90:driver:compute_zdep
get_useparameters: no module sps_vars info used by compute_zdep
                Block: get_spec
In: :_fsps:fsps.f90:driver:get_spec
get_useparameters: no module sps_utils info used by get_spec
In: :_fsps:fsps.f90:driver:get_spec
get_useparameters: no module sps_vars info used by get_spec
                Block: get_mags
In: :_fsps:fsps.f90:driver:get_mags
get_useparameters: no module sps_utils info used by get_mags
In: :_fsps:fsps.f90:driver:get_mags
get_useparameters: no module sps_vars info used by get_mags
                Block: stellar_spectrum
In: :_fsps:fsps.f90:driver:stellar_spectrum
get_useparameters: no module sps_utils info used by stellar_spectrum
In: :_fsps:fsps.f90:driver:stellar_spectrum
get_useparameters: no module sps_vars info used by stellar_spectrum
                Block: get_setup_vars
In: :_fsps:fsps.f90:driver:get_setup_vars
get_useparameters: no module sps_utils info used by get_setup_vars
In: :_fsps:fsps.f90:driver:get_setup_vars
get_useparameters: no module sps_vars info used by get_setup_vars
                Block: get_nz
In: :_fsps:fsps.f90:driver:get_nz
get_useparameters: no module sps_utils info used by get_nz
In: :_fsps:fsps.f90:driver:get_nz
get_useparameters: no module sps_vars info used by get_nz
                Block: get_zlegend
In: :_fsps:fsps.f90:driver:get_zlegend
get_useparameters: no module sps_utils info used by get_zlegend
In: :_fsps:fsps.f90:driver:get_zlegend
get_useparameters: no module sps_vars info used by get_zlegend
                Block: get_timefull
In: :_fsps:fsps.f90:driver:get_timefull
get_useparameters: no module sps_utils info used by get_timefull
In: :_fsps:fsps.f90:driver:get_timefull
get_useparameters: no module sps_vars info used by get_timefull
                Block: get_ntfull
In: :_fsps:fsps.f90:driver:get_ntfull
get_useparameters: no module sps_utils info used by get_ntfull
In: :_fsps:fsps.f90:driver:get_ntfull
get_useparameters: no module sps_vars info used by get_ntfull
                Block: get_nspec
In: :_fsps:fsps.f90:driver:get_nspec
get_useparameters: no module sps_utils info used by get_nspec
In: :_fsps:fsps.f90:driver:get_nspec
get_useparameters: no module sps_vars info used by get_nspec
                Block: get_nbands
In: :_fsps:fsps.f90:driver:get_nbands
get_useparameters: no module sps_utils info used by get_nbands
In: :_fsps:fsps.f90:driver:get_nbands
get_useparameters: no module sps_vars info used by get_nbands
                Block: get_lambda
In: :_fsps:fsps.f90:driver:get_lambda
get_useparameters: no module sps_utils info used by get_lambda
In: :_fsps:fsps.f90:driver:get_lambda
get_useparameters: no module sps_vars info used by get_lambda
                Block: get_isochrone_dimensions
In: :_fsps:fsps.f90:driver:get_isochrone_dimensions
get_useparameters: no module sps_utils info used by get_isochrone_dimensions
In: :_fsps:fsps.f90:driver:get_isochrone_dimensions
get_useparameters: no module sps_vars info used by get_isochrone_dimensions
                Block: get_nmass_isochrone
In: :_fsps:fsps.f90:driver:get_nmass_isochrone
get_useparameters: no module sps_utils info used by get_nmass_isochrone
In: :_fsps:fsps.f90:driver:get_nmass_isochrone
get_useparameters: no module sps_vars info used by get_nmass_isochrone
                Block: get_stats
In: :_fsps:fsps.f90:driver:get_stats
get_useparameters: no module sps_utils info used by get_stats
In: :_fsps:fsps.f90:driver:get_stats
get_useparameters: no module sps_vars info used by get_stats
                Block: write_isoc
In: :_fsps:fsps.f90:driver:write_isoc
get_useparameters: no module sps_utils info used by write_isoc
In: :_fsps:fsps.f90:driver:write_isoc
get_useparameters: no module sps_vars info used by write_isoc
Post-processing (stage 2)...
    Block: _fsps
        Block: unknown_interface
            Block: driver
                Block: setup
                Block: set_ssp_params
                Block: set_csp_params
                Block: ssps
                Block: ssp
                Block: get_ssp_spec
                Block: interp_ssp
                Block: smooth_spectrum
                Block: compute
                Block: compute_zdep
                Block: get_spec
                Block: get_mags
                Block: stellar_spectrum
                Block: get_setup_vars
                Block: get_nz
                Block: get_zlegend
                Block: get_timefull
                Block: get_ntfull
                Block: get_nspec
                Block: get_nbands
                Block: get_lambda
                Block: get_isochrone_dimensions
                Block: get_nmass_isochrone
                Block: get_stats
                Block: write_isoc
Saving signatures to file "./fsps.pyf"
Running f2py on ['/Users/Nell/programs/fsps/src/add_agb_dust.o', '/Users/Nell/programs/fsps/src/add_bs.o', '/Users/Nell/programs/fsps/src/add_dust.o', '/Users/Nell/programs/fsps/src/add_nebular.o', '/Users/Nell/programs/fsps/src/add_remnants.o', '/Users/Nell/programs/fsps/src/compsp.o', '/Users/Nell/programs/fsps/src/funcint.o', '/Users/Nell/programs/fsps/src/get_lumdist.o', '/Users/Nell/programs/fsps/src/get_tuniv.o', '/Users/Nell/programs/fsps/src/getindx.o', '/Users/Nell/programs/fsps/src/getmags.o', '/Users/Nell/programs/fsps/src/getspec.o', '/Users/Nell/programs/fsps/src/igm_absorb.o', '/Users/Nell/programs/fsps/src/imf.o', '/Users/Nell/programs/fsps/src/imf_weight.o', '/Users/Nell/programs/fsps/src/intsfr.o', '/Users/Nell/programs/fsps/src/intspec.o', '/Users/Nell/programs/fsps/src/linterp.o', '/Users/Nell/programs/fsps/src/linterparr.o', '/Users/Nell/programs/fsps/src/locate.o', '/Users/Nell/programs/fsps/src/mod_gb.o', '/Users/Nell/programs/fsps/src/mod_hb.o', '/Users/Nell/programs/fsps/src/pz_convol.o', '/Users/Nell/programs/fsps/src/sbf.o', '/Users/Nell/programs/fsps/src/sfhstat.o', '/Users/Nell/programs/fsps/src/smoothspec.o', '/Users/Nell/programs/fsps/src/sps_setup.o', '/Users/Nell/programs/fsps/src/sps_utils.o', '/Users/Nell/programs/fsps/src/sps_vars.o', '/Users/Nell/programs/fsps/src/ssp_gen.o', '/Users/Nell/programs/fsps/src/tsum.o', '/Users/Nell/programs/fsps/src/vacairconv.o', '/Users/Nell/programs/fsps/src/write_isochrone.o', '/Users/Nell/programs/fsps/src/ztinterp.o', 'fsps.f90', 'fsps.pyf'] with flags ['-c', '-I/Users/Nell/programs/fsps/src', '--f90flags=-cpp', '--f90flags=-fPIC']
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "_fsps" sources
creating /var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmp3xBgBt/src.macosx-10.11-x86_64-2.7
f2py options: []
f2py: fsps.pyf
Reading fortran codes...
    Reading file 'fsps.pyf' (format:free)
Post-processing...
    Block: _fsps
            Block: driver
In: fsps.pyf:_fsps:unknown_interface:driver
get_useparameters: no module sps_utils info used by driver
In: fsps.pyf:_fsps:unknown_interface:driver
get_useparameters: no module sps_vars info used by driver
                Block: setup
In: fsps.pyf:_fsps:unknown_interface:driver:setup
get_useparameters: no module sps_utils info used by setup
In: fsps.pyf:_fsps:unknown_interface:driver:setup
get_useparameters: no module sps_vars info used by setup
                Block: set_ssp_params
In: fsps.pyf:_fsps:unknown_interface:driver:set_ssp_params
get_useparameters: no module sps_utils info used by set_ssp_params
In: fsps.pyf:_fsps:unknown_interface:driver:set_ssp_params
get_useparameters: no module sps_vars info used by set_ssp_params
                Block: set_csp_params
In: fsps.pyf:_fsps:unknown_interface:driver:set_csp_params
get_useparameters: no module sps_utils info used by set_csp_params
In: fsps.pyf:_fsps:unknown_interface:driver:set_csp_params
get_useparameters: no module sps_vars info used by set_csp_params
                Block: ssps
In: fsps.pyf:_fsps:unknown_interface:driver:ssps
get_useparameters: no module sps_utils info used by ssps
In: fsps.pyf:_fsps:unknown_interface:driver:ssps
get_useparameters: no module sps_vars info used by ssps
                Block: ssp
In: fsps.pyf:_fsps:unknown_interface:driver:ssp
get_useparameters: no module sps_utils info used by ssp
In: fsps.pyf:_fsps:unknown_interface:driver:ssp
get_useparameters: no module sps_vars info used by ssp
                Block: get_ssp_spec
In: fsps.pyf:_fsps:unknown_interface:driver:get_ssp_spec
get_useparameters: no module sps_utils info used by get_ssp_spec
In: fsps.pyf:_fsps:unknown_interface:driver:get_ssp_spec
get_useparameters: no module sps_vars info used by get_ssp_spec
                Block: interp_ssp
In: fsps.pyf:_fsps:unknown_interface:driver:interp_ssp
get_useparameters: no module sps_utils info used by interp_ssp
In: fsps.pyf:_fsps:unknown_interface:driver:interp_ssp
get_useparameters: no module sps_vars info used by interp_ssp
                Block: smooth_spectrum
In: fsps.pyf:_fsps:unknown_interface:driver:smooth_spectrum
get_useparameters: no module sps_utils info used by smooth_spectrum
In: fsps.pyf:_fsps:unknown_interface:driver:smooth_spectrum
get_useparameters: no module sps_vars info used by smooth_spectrum
                Block: compute
In: fsps.pyf:_fsps:unknown_interface:driver:compute
get_useparameters: no module sps_utils info used by compute
In: fsps.pyf:_fsps:unknown_interface:driver:compute
get_useparameters: no module sps_vars info used by compute
                Block: compute_zdep
In: fsps.pyf:_fsps:unknown_interface:driver:compute_zdep
get_useparameters: no module sps_utils info used by compute_zdep
In: fsps.pyf:_fsps:unknown_interface:driver:compute_zdep
get_useparameters: no module sps_vars info used by compute_zdep
                Block: get_spec
In: fsps.pyf:_fsps:unknown_interface:driver:get_spec
get_useparameters: no module sps_utils info used by get_spec
In: fsps.pyf:_fsps:unknown_interface:driver:get_spec
get_useparameters: no module sps_vars info used by get_spec
                Block: get_mags
In: fsps.pyf:_fsps:unknown_interface:driver:get_mags
get_useparameters: no module sps_utils info used by get_mags
In: fsps.pyf:_fsps:unknown_interface:driver:get_mags
get_useparameters: no module sps_vars info used by get_mags
                Block: stellar_spectrum
In: fsps.pyf:_fsps:unknown_interface:driver:stellar_spectrum
get_useparameters: no module sps_utils info used by stellar_spectrum
In: fsps.pyf:_fsps:unknown_interface:driver:stellar_spectrum
get_useparameters: no module sps_vars info used by stellar_spectrum
                Block: get_setup_vars
In: fsps.pyf:_fsps:unknown_interface:driver:get_setup_vars
get_useparameters: no module sps_utils info used by get_setup_vars
In: fsps.pyf:_fsps:unknown_interface:driver:get_setup_vars
get_useparameters: no module sps_vars info used by get_setup_vars
                Block: get_nz
In: fsps.pyf:_fsps:unknown_interface:driver:get_nz
get_useparameters: no module sps_utils info used by get_nz
In: fsps.pyf:_fsps:unknown_interface:driver:get_nz
get_useparameters: no module sps_vars info used by get_nz
                Block: get_zlegend
In: fsps.pyf:_fsps:unknown_interface:driver:get_zlegend
get_useparameters: no module sps_utils info used by get_zlegend
In: fsps.pyf:_fsps:unknown_interface:driver:get_zlegend
get_useparameters: no module sps_vars info used by get_zlegend
                Block: get_timefull
In: fsps.pyf:_fsps:unknown_interface:driver:get_timefull
get_useparameters: no module sps_utils info used by get_timefull
In: fsps.pyf:_fsps:unknown_interface:driver:get_timefull
get_useparameters: no module sps_vars info used by get_timefull
                Block: get_ntfull
In: fsps.pyf:_fsps:unknown_interface:driver:get_ntfull
get_useparameters: no module sps_utils info used by get_ntfull
In: fsps.pyf:_fsps:unknown_interface:driver:get_ntfull
get_useparameters: no module sps_vars info used by get_ntfull
                Block: get_nspec
In: fsps.pyf:_fsps:unknown_interface:driver:get_nspec
get_useparameters: no module sps_utils info used by get_nspec
In: fsps.pyf:_fsps:unknown_interface:driver:get_nspec
get_useparameters: no module sps_vars info used by get_nspec
                Block: get_nbands
In: fsps.pyf:_fsps:unknown_interface:driver:get_nbands
get_useparameters: no module sps_utils info used by get_nbands
In: fsps.pyf:_fsps:unknown_interface:driver:get_nbands
get_useparameters: no module sps_vars info used by get_nbands
                Block: get_lambda
In: fsps.pyf:_fsps:unknown_interface:driver:get_lambda
get_useparameters: no module sps_utils info used by get_lambda
In: fsps.pyf:_fsps:unknown_interface:driver:get_lambda
get_useparameters: no module sps_vars info used by get_lambda
                Block: get_isochrone_dimensions
In: fsps.pyf:_fsps:unknown_interface:driver:get_isochrone_dimensions
get_useparameters: no module sps_utils info used by get_isochrone_dimensions
In: fsps.pyf:_fsps:unknown_interface:driver:get_isochrone_dimensions
get_useparameters: no module sps_vars info used by get_isochrone_dimensions
                Block: get_nmass_isochrone
In: fsps.pyf:_fsps:unknown_interface:driver:get_nmass_isochrone
get_useparameters: no module sps_utils info used by get_nmass_isochrone
In: fsps.pyf:_fsps:unknown_interface:driver:get_nmass_isochrone
get_useparameters: no module sps_vars info used by get_nmass_isochrone
                Block: get_stats
In: fsps.pyf:_fsps:unknown_interface:driver:get_stats
get_useparameters: no module sps_utils info used by get_stats
In: fsps.pyf:_fsps:unknown_interface:driver:get_stats
get_useparameters: no module sps_vars info used by get_stats
                Block: write_isoc
In: fsps.pyf:_fsps:unknown_interface:driver:write_isoc
get_useparameters: no module sps_utils info used by write_isoc
In: fsps.pyf:_fsps:unknown_interface:driver:write_isoc
get_useparameters: no module sps_vars info used by write_isoc
Post-processing (stage 2)...
    Block: _fsps
        Block: unknown_interface
            Block: driver
                Block: setup
                Block: set_ssp_params
                Block: set_csp_params
                Block: ssps
                Block: ssp
                Block: get_ssp_spec
                Block: interp_ssp
                Block: smooth_spectrum
                Block: compute
                Block: compute_zdep
                Block: get_spec
                Block: get_mags
                Block: stellar_spectrum
                Block: get_setup_vars
                Block: get_nz
                Block: get_zlegend
                Block: get_timefull
                Block: get_ntfull
                Block: get_nspec
                Block: get_nbands
                Block: get_lambda
                Block: get_isochrone_dimensions
                Block: get_nmass_isochrone
                Block: get_stats
                Block: write_isoc
Building modules...
    Building module "_fsps"...
        Constructing F90 module support for "driver"...
          Variables: pset is_setup ocompsp has_ssp has_ssp_age
getctype: No C-type found in "{'typespec': 'type', 'typename': 'params'}", assuming void.
Traceback (most recent call last):
  File "setup.py", line 121, in <module>
    "Programming Language :: Python",
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 160, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 146, in call_command
    self.run_command(cmdname)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/install_lib.py", line 10, in run
    self.build()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 61, in run
    invoke_f2py(fns, flags, wd='fsps')
  File "setup.py", line 28, in invoke_f2py
    main()
  File "/usr/local/lib/python2.7/site-packages/numpy/f2py/f2py2e.py", line 648, in main
    run_compile()
  File "/usr/local/lib/python2.7/site-packages/numpy/f2py/f2py2e.py", line 633, in run_compile
    setup(ext_modules=[ext])
  File "/usr/local/lib/python2.7/site-packages/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/site-packages/numpy/distutils/command/build.py", line 47, in run
    old_build.run(self)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/site-packages/numpy/distutils/command/build_src.py", line 153, in run
    self.build_sources()
  File "/usr/local/lib/python2.7/site-packages/numpy/distutils/command/build_src.py", line 170, in build_sources
    self.build_extension_sources(ext)
  File "/usr/local/lib/python2.7/site-packages/numpy/distutils/command/build_src.py", line 335, in build_extension_sources
    sources = self.f2py_sources(sources, ext)
  File "/usr/local/lib/python2.7/site-packages/numpy/distutils/command/build_src.py", line 574, in f2py_sources
    + ['--build-dir', target_dir, source])
  File "/usr/local/lib/python2.7/site-packages/numpy/f2py/f2py2e.py", line 440, in run_main
    ret = buildmodules(postlist)
  File "/usr/local/lib/python2.7/site-packages/numpy/f2py/f2py2e.py", line 384, in buildmodules
    dict_append(ret[mnames[i]], rules.buildmodule(modules[i], um))
  File "/usr/local/lib/python2.7/site-packages/numpy/f2py/rules.py", line 1213, in buildmodule
    mr, wrap = f90mod_rules.buildhooks(m)
  File "/usr/local/lib/python2.7/site-packages/numpy/f2py/f90mod_rules.py", line 146, in buildhooks
    at = capi_maps.c2capi_map[ct]
KeyError: 'void'
---
## and here is the output from running setup.py with numpy 1.8.2:

running install
running bdist_egg
running egg_info
writing fsps.egg-info/PKG-INFO
writing top-level names to fsps.egg-info/top_level.txt
writing dependency_links to fsps.egg-info/dependency_links.txt
reading manifest file 'fsps.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'fsps.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.11-x86_64/egg
running install_lib
running build_py
running build_ext
Running f2py on ['fsps.f90'] with flags ['-m', '_fsps', '-h', 'fsps.pyf', '--overwrite-signature']
Reading fortran codes...
    Reading file 'fsps.f90' (format:free)
rmbadname1: Replacing "const" with "const_bn".
rmbadname1: Replacing "const" with "const_bn".
Post-processing...
    Block: _fsps
            Block: driver
In: :_fsps:fsps.f90:driver
get_useparameters: no module sps_utils info used by driver
In: :_fsps:fsps.f90:driver
get_useparameters: no module sps_vars info used by driver
In: :_fsps:fsps.f90:driver
    getarrlen:variable "ntfull" undefined
In: :_fsps:fsps.f90:driver
    getarrlen:variable "nz" undefined
In: :_fsps:fsps.f90:driver
    getarrlen:variable "nz" undefined
In: :_fsps:fsps.f90:driver
    getarrlen:variable "nt" undefined
                Block: setup
In: :_fsps:fsps.f90:driver:setup
get_useparameters: no module sps_utils info used by setup
In: :_fsps:fsps.f90:driver:setup
get_useparameters: no module sps_vars info used by setup
                Block: set_ssp_params
In: :_fsps:fsps.f90:driver:set_ssp_params
get_useparameters: no module sps_utils info used by set_ssp_params
In: :_fsps:fsps.f90:driver:set_ssp_params
get_useparameters: no module sps_vars info used by set_ssp_params
                Block: set_csp_params
In: :_fsps:fsps.f90:driver:set_csp_params
get_useparameters: no module sps_utils info used by set_csp_params
In: :_fsps:fsps.f90:driver:set_csp_params
get_useparameters: no module sps_vars info used by set_csp_params
                Block: ssps
In: :_fsps:fsps.f90:driver:ssps
get_useparameters: no module sps_utils info used by ssps
In: :_fsps:fsps.f90:driver:ssps
get_useparameters: no module sps_vars info used by ssps
                Block: ssp
In: :_fsps:fsps.f90:driver:ssp
get_useparameters: no module sps_utils info used by ssp
In: :_fsps:fsps.f90:driver:ssp
get_useparameters: no module sps_vars info used by ssp
                Block: get_ssp_spec
In: :_fsps:fsps.f90:driver:get_ssp_spec
get_useparameters: no module sps_utils info used by get_ssp_spec
In: :_fsps:fsps.f90:driver:get_ssp_spec
get_useparameters: no module sps_vars info used by get_ssp_spec
                Block: interp_ssp
In: :_fsps:fsps.f90:driver:interp_ssp
get_useparameters: no module sps_utils info used by interp_ssp
In: :_fsps:fsps.f90:driver:interp_ssp
get_useparameters: no module sps_vars info used by interp_ssp
In: :_fsps:fsps.f90:driver:interp_ssp
    getarrlen:variable "nt" undefined
                Block: smooth_spectrum
In: :_fsps:fsps.f90:driver:smooth_spectrum
get_useparameters: no module sps_utils info used by smooth_spectrum
In: :_fsps:fsps.f90:driver:smooth_spectrum
get_useparameters: no module sps_vars info used by smooth_spectrum
                Block: compute
In: :_fsps:fsps.f90:driver:compute
get_useparameters: no module sps_utils info used by compute
In: :_fsps:fsps.f90:driver:compute
get_useparameters: no module sps_vars info used by compute
                Block: compute_zdep
In: :_fsps:fsps.f90:driver:compute_zdep
get_useparameters: no module sps_utils info used by compute_zdep
In: :_fsps:fsps.f90:driver:compute_zdep
get_useparameters: no module sps_vars info used by compute_zdep
                Block: get_spec
In: :_fsps:fsps.f90:driver:get_spec
get_useparameters: no module sps_utils info used by get_spec
In: :_fsps:fsps.f90:driver:get_spec
get_useparameters: no module sps_vars info used by get_spec
                Block: get_mags
In: :_fsps:fsps.f90:driver:get_mags
get_useparameters: no module sps_utils info used by get_mags
In: :_fsps:fsps.f90:driver:get_mags
get_useparameters: no module sps_vars info used by get_mags
                Block: stellar_spectrum
In: :_fsps:fsps.f90:driver:stellar_spectrum
get_useparameters: no module sps_utils info used by stellar_spectrum
In: :_fsps:fsps.f90:driver:stellar_spectrum
get_useparameters: no module sps_vars info used by stellar_spectrum
                Block: get_setup_vars
In: :_fsps:fsps.f90:driver:get_setup_vars
get_useparameters: no module sps_utils info used by get_setup_vars
In: :_fsps:fsps.f90:driver:get_setup_vars
get_useparameters: no module sps_vars info used by get_setup_vars
                Block: get_nz
In: :_fsps:fsps.f90:driver:get_nz
get_useparameters: no module sps_utils info used by get_nz
In: :_fsps:fsps.f90:driver:get_nz
get_useparameters: no module sps_vars info used by get_nz
                Block: get_zlegend
In: :_fsps:fsps.f90:driver:get_zlegend
get_useparameters: no module sps_utils info used by get_zlegend
In: :_fsps:fsps.f90:driver:get_zlegend
get_useparameters: no module sps_vars info used by get_zlegend
                Block: get_timefull
In: :_fsps:fsps.f90:driver:get_timefull
get_useparameters: no module sps_utils info used by get_timefull
In: :_fsps:fsps.f90:driver:get_timefull
get_useparameters: no module sps_vars info used by get_timefull
                Block: get_ntfull
In: :_fsps:fsps.f90:driver:get_ntfull
get_useparameters: no module sps_utils info used by get_ntfull
In: :_fsps:fsps.f90:driver:get_ntfull
get_useparameters: no module sps_vars info used by get_ntfull
                Block: get_nspec
In: :_fsps:fsps.f90:driver:get_nspec
get_useparameters: no module sps_utils info used by get_nspec
In: :_fsps:fsps.f90:driver:get_nspec
get_useparameters: no module sps_vars info used by get_nspec
                Block: get_nbands
In: :_fsps:fsps.f90:driver:get_nbands
get_useparameters: no module sps_utils info used by get_nbands
In: :_fsps:fsps.f90:driver:get_nbands
get_useparameters: no module sps_vars info used by get_nbands
                Block: get_lambda
In: :_fsps:fsps.f90:driver:get_lambda
get_useparameters: no module sps_utils info used by get_lambda
In: :_fsps:fsps.f90:driver:get_lambda
get_useparameters: no module sps_vars info used by get_lambda
                Block: get_isochrone_dimensions
In: :_fsps:fsps.f90:driver:get_isochrone_dimensions
get_useparameters: no module sps_utils info used by get_isochrone_dimensions
In: :_fsps:fsps.f90:driver:get_isochrone_dimensions
get_useparameters: no module sps_vars info used by get_isochrone_dimensions
                Block: get_nmass_isochrone
In: :_fsps:fsps.f90:driver:get_nmass_isochrone
get_useparameters: no module sps_utils info used by get_nmass_isochrone
In: :_fsps:fsps.f90:driver:get_nmass_isochrone
get_useparameters: no module sps_vars info used by get_nmass_isochrone
                Block: get_stats
In: :_fsps:fsps.f90:driver:get_stats
get_useparameters: no module sps_utils info used by get_stats
In: :_fsps:fsps.f90:driver:get_stats
get_useparameters: no module sps_vars info used by get_stats
                Block: write_isoc
In: :_fsps:fsps.f90:driver:write_isoc
get_useparameters: no module sps_utils info used by write_isoc
In: :_fsps:fsps.f90:driver:write_isoc
get_useparameters: no module sps_vars info used by write_isoc
Post-processing (stage 2)...
    Block: _fsps
        Block: unknown_interface
            Block: driver
                Block: setup
                Block: set_ssp_params
                Block: set_csp_params
                Block: ssps
                Block: ssp
                Block: get_ssp_spec
                Block: interp_ssp
                Block: smooth_spectrum
                Block: compute
                Block: compute_zdep
                Block: get_spec
                Block: get_mags
                Block: stellar_spectrum
                Block: get_setup_vars
                Block: get_nz
                Block: get_zlegend
                Block: get_timefull
                Block: get_ntfull
                Block: get_nspec
                Block: get_nbands
                Block: get_lambda
                Block: get_isochrone_dimensions
                Block: get_nmass_isochrone
                Block: get_stats
                Block: write_isoc
Saving signatures to file "./fsps.pyf"
Running f2py on ['/Users/Nell/programs/fsps/src/add_agb_dust.o', '/Users/Nell/programs/fsps/src/add_bs.o', '/Users/Nell/programs/fsps/src/add_dust.o', '/Users/Nell/programs/fsps/src/add_nebular.o', '/Users/Nell/programs/fsps/src/add_remnants.o', '/Users/Nell/programs/fsps/src/compsp.o', '/Users/Nell/programs/fsps/src/funcint.o', '/Users/Nell/programs/fsps/src/get_lumdist.o', '/Users/Nell/programs/fsps/src/get_tuniv.o', '/Users/Nell/programs/fsps/src/getindx.o', '/Users/Nell/programs/fsps/src/getmags.o', '/Users/Nell/programs/fsps/src/getspec.o', '/Users/Nell/programs/fsps/src/igm_absorb.o', '/Users/Nell/programs/fsps/src/imf.o', '/Users/Nell/programs/fsps/src/imf_weight.o', '/Users/Nell/programs/fsps/src/intsfr.o', '/Users/Nell/programs/fsps/src/intspec.o', '/Users/Nell/programs/fsps/src/linterp.o', '/Users/Nell/programs/fsps/src/linterparr.o', '/Users/Nell/programs/fsps/src/locate.o', '/Users/Nell/programs/fsps/src/mod_gb.o', '/Users/Nell/programs/fsps/src/mod_hb.o', '/Users/Nell/programs/fsps/src/pz_convol.o', '/Users/Nell/programs/fsps/src/sbf.o', '/Users/Nell/programs/fsps/src/sfhstat.o', '/Users/Nell/programs/fsps/src/smoothspec.o', '/Users/Nell/programs/fsps/src/sps_setup.o', '/Users/Nell/programs/fsps/src/sps_utils.o', '/Users/Nell/programs/fsps/src/sps_vars.o', '/Users/Nell/programs/fsps/src/ssp_gen.o', '/Users/Nell/programs/fsps/src/tsum.o', '/Users/Nell/programs/fsps/src/vacairconv.o', '/Users/Nell/programs/fsps/src/write_isochrone.o', '/Users/Nell/programs/fsps/src/ztinterp.o', 'fsps.f90', 'fsps.pyf'] with flags ['-c', '-I/Users/Nell/programs/fsps/src', '--f90flags=-cpp', '--f90flags=-fPIC']
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "_fsps" sources
creating /var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/src.macosx-10.11-x86_64-2.7
f2py options: []
f2py: fsps.pyf
Reading fortran codes...
    Reading file 'fsps.pyf' (format:free)
Post-processing...
    Block: _fsps
            Block: driver
In: fsps.pyf:_fsps:unknown_interface:driver
get_useparameters: no module sps_utils info used by driver
In: fsps.pyf:_fsps:unknown_interface:driver
get_useparameters: no module sps_vars info used by driver
                Block: setup
In: fsps.pyf:_fsps:unknown_interface:driver:setup
get_useparameters: no module sps_utils info used by setup
In: fsps.pyf:_fsps:unknown_interface:driver:setup
get_useparameters: no module sps_vars info used by setup
                Block: set_ssp_params
In: fsps.pyf:_fsps:unknown_interface:driver:set_ssp_params
get_useparameters: no module sps_utils info used by set_ssp_params
In: fsps.pyf:_fsps:unknown_interface:driver:set_ssp_params
get_useparameters: no module sps_vars info used by set_ssp_params
                Block: set_csp_params
In: fsps.pyf:_fsps:unknown_interface:driver:set_csp_params
get_useparameters: no module sps_utils info used by set_csp_params
In: fsps.pyf:_fsps:unknown_interface:driver:set_csp_params
get_useparameters: no module sps_vars info used by set_csp_params
                Block: ssps
In: fsps.pyf:_fsps:unknown_interface:driver:ssps
get_useparameters: no module sps_utils info used by ssps
In: fsps.pyf:_fsps:unknown_interface:driver:ssps
get_useparameters: no module sps_vars info used by ssps
                Block: ssp
In: fsps.pyf:_fsps:unknown_interface:driver:ssp
get_useparameters: no module sps_utils info used by ssp
In: fsps.pyf:_fsps:unknown_interface:driver:ssp
get_useparameters: no module sps_vars info used by ssp
                Block: get_ssp_spec
In: fsps.pyf:_fsps:unknown_interface:driver:get_ssp_spec
get_useparameters: no module sps_utils info used by get_ssp_spec
In: fsps.pyf:_fsps:unknown_interface:driver:get_ssp_spec
get_useparameters: no module sps_vars info used by get_ssp_spec
                Block: interp_ssp
In: fsps.pyf:_fsps:unknown_interface:driver:interp_ssp
get_useparameters: no module sps_utils info used by interp_ssp
In: fsps.pyf:_fsps:unknown_interface:driver:interp_ssp
get_useparameters: no module sps_vars info used by interp_ssp
                Block: smooth_spectrum
In: fsps.pyf:_fsps:unknown_interface:driver:smooth_spectrum
get_useparameters: no module sps_utils info used by smooth_spectrum
In: fsps.pyf:_fsps:unknown_interface:driver:smooth_spectrum
get_useparameters: no module sps_vars info used by smooth_spectrum
                Block: compute
In: fsps.pyf:_fsps:unknown_interface:driver:compute
get_useparameters: no module sps_utils info used by compute
In: fsps.pyf:_fsps:unknown_interface:driver:compute
get_useparameters: no module sps_vars info used by compute
                Block: compute_zdep
In: fsps.pyf:_fsps:unknown_interface:driver:compute_zdep
get_useparameters: no module sps_utils info used by compute_zdep
In: fsps.pyf:_fsps:unknown_interface:driver:compute_zdep
get_useparameters: no module sps_vars info used by compute_zdep
                Block: get_spec
In: fsps.pyf:_fsps:unknown_interface:driver:get_spec
get_useparameters: no module sps_utils info used by get_spec
In: fsps.pyf:_fsps:unknown_interface:driver:get_spec
get_useparameters: no module sps_vars info used by get_spec
                Block: get_mags
In: fsps.pyf:_fsps:unknown_interface:driver:get_mags
get_useparameters: no module sps_utils info used by get_mags
In: fsps.pyf:_fsps:unknown_interface:driver:get_mags
get_useparameters: no module sps_vars info used by get_mags
                Block: stellar_spectrum
In: fsps.pyf:_fsps:unknown_interface:driver:stellar_spectrum
get_useparameters: no module sps_utils info used by stellar_spectrum
In: fsps.pyf:_fsps:unknown_interface:driver:stellar_spectrum
get_useparameters: no module sps_vars info used by stellar_spectrum
                Block: get_setup_vars
In: fsps.pyf:_fsps:unknown_interface:driver:get_setup_vars
get_useparameters: no module sps_utils info used by get_setup_vars
In: fsps.pyf:_fsps:unknown_interface:driver:get_setup_vars
get_useparameters: no module sps_vars info used by get_setup_vars
                Block: get_nz
In: fsps.pyf:_fsps:unknown_interface:driver:get_nz
get_useparameters: no module sps_utils info used by get_nz
In: fsps.pyf:_fsps:unknown_interface:driver:get_nz
get_useparameters: no module sps_vars info used by get_nz
                Block: get_zlegend
In: fsps.pyf:_fsps:unknown_interface:driver:get_zlegend
get_useparameters: no module sps_utils info used by get_zlegend
In: fsps.pyf:_fsps:unknown_interface:driver:get_zlegend
get_useparameters: no module sps_vars info used by get_zlegend
                Block: get_timefull
In: fsps.pyf:_fsps:unknown_interface:driver:get_timefull
get_useparameters: no module sps_utils info used by get_timefull
In: fsps.pyf:_fsps:unknown_interface:driver:get_timefull
get_useparameters: no module sps_vars info used by get_timefull
                Block: get_ntfull
In: fsps.pyf:_fsps:unknown_interface:driver:get_ntfull
get_useparameters: no module sps_utils info used by get_ntfull
In: fsps.pyf:_fsps:unknown_interface:driver:get_ntfull
get_useparameters: no module sps_vars info used by get_ntfull
                Block: get_nspec
In: fsps.pyf:_fsps:unknown_interface:driver:get_nspec
get_useparameters: no module sps_utils info used by get_nspec
In: fsps.pyf:_fsps:unknown_interface:driver:get_nspec
get_useparameters: no module sps_vars info used by get_nspec
                Block: get_nbands
In: fsps.pyf:_fsps:unknown_interface:driver:get_nbands
get_useparameters: no module sps_utils info used by get_nbands
In: fsps.pyf:_fsps:unknown_interface:driver:get_nbands
get_useparameters: no module sps_vars info used by get_nbands
                Block: get_lambda
In: fsps.pyf:_fsps:unknown_interface:driver:get_lambda
get_useparameters: no module sps_utils info used by get_lambda
In: fsps.pyf:_fsps:unknown_interface:driver:get_lambda
get_useparameters: no module sps_vars info used by get_lambda
                Block: get_isochrone_dimensions
In: fsps.pyf:_fsps:unknown_interface:driver:get_isochrone_dimensions
get_useparameters: no module sps_utils info used by get_isochrone_dimensions
In: fsps.pyf:_fsps:unknown_interface:driver:get_isochrone_dimensions
get_useparameters: no module sps_vars info used by get_isochrone_dimensions
                Block: get_nmass_isochrone
In: fsps.pyf:_fsps:unknown_interface:driver:get_nmass_isochrone
get_useparameters: no module sps_utils info used by get_nmass_isochrone
In: fsps.pyf:_fsps:unknown_interface:driver:get_nmass_isochrone
get_useparameters: no module sps_vars info used by get_nmass_isochrone
                Block: get_stats
In: fsps.pyf:_fsps:unknown_interface:driver:get_stats
get_useparameters: no module sps_utils info used by get_stats
In: fsps.pyf:_fsps:unknown_interface:driver:get_stats
get_useparameters: no module sps_vars info used by get_stats
                Block: write_isoc
In: fsps.pyf:_fsps:unknown_interface:driver:write_isoc
get_useparameters: no module sps_utils info used by write_isoc
In: fsps.pyf:_fsps:unknown_interface:driver:write_isoc
get_useparameters: no module sps_vars info used by write_isoc
Post-processing (stage 2)...
    Block: _fsps
        Block: unknown_interface
            Block: driver
                Block: setup
                Block: set_ssp_params
                Block: set_csp_params
                Block: ssps
                Block: ssp
                Block: get_ssp_spec
                Block: interp_ssp
                Block: smooth_spectrum
                Block: compute
                Block: compute_zdep
                Block: get_spec
                Block: get_mags
                Block: stellar_spectrum
                Block: get_setup_vars
                Block: get_nz
                Block: get_zlegend
                Block: get_timefull
                Block: get_ntfull
                Block: get_nspec
                Block: get_nbands
                Block: get_lambda
                Block: get_isochrone_dimensions
                Block: get_nmass_isochrone
                Block: get_stats
                Block: write_isoc
Building modules...
    Building module "_fsps"...
        Constructing F90 module support for "driver"...
          Variables: is_setup
            Constructing wrapper function "driver.setup"...
              setup(compute_vega_mags0)
            Constructing wrapper function "driver.set_ssp_params"...
              set_ssp_params(imf_type0,imf1,imf2,imf3,vdmc,mdave,dell,delt,sbss,fbhb,pagb,add_stellar_remnants0,tpagb_norm_type0,add_agb_dust_model0,agb_dust,redgb,masscut,fcstar,evtype)
            Constructing wrapper function "driver.set_csp_params"...
              set_csp_params(smooth_velocity0,vactoair_flag0,redshift_colors0,dust_type0,add_dust_emission0,add_neb_emission0,add_neb_continuum0,cloudy_dust0,add_igm_absorption0,zmet,sfh,wgp1,wgp2,wgp3,tau,const_bn,tage,fburst,tburst,dust1,dust2,logzsol,zred,pmetals,dust_clumps,frac_nodust,dust_index,dust_tesc,frac_obrun,uvb,mwr,dust1_index,sf_start,sf_trunc,sf_slope,duste_gamma,duste_umin,duste_qpah,sigma_smooth,min_wave_smooth,max_wave_smooth,gas_logu,gas_logz,igm_factor)
            Constructing wrapper function "driver.ssps"...
              ssps()
            Constructing wrapper function "driver.ssp"...
              ssp(zi)
            Constructing wrapper function "driver.get_ssp_spec"...
              get_ssp_spec(ssp_spec_out,ssp_mass_out,ssp_lbol_out,[ns,n_age,n_z])
            Constructing wrapper function "driver.interp_ssp"...
              interp_ssp(zpos,tpos,spec,mass,lbol,[ns])
            Constructing wrapper function "driver.smooth_spectrum"...
              smooth_spectrum(wave,spec,sigma_broad,minw,maxw,[ns])
            Constructing wrapper function "driver.compute"...
              compute()
            Constructing wrapper function "driver.compute_zdep"...
              compute_zdep(ns,n_age,ztype)
            Constructing wrapper function "driver.get_spec"...
              spec_out = get_spec(ns,n_age)
            Constructing wrapper function "driver.get_mags"...
              mags = get_mags(ns,n_age,z_red,mc,[n_bands])
            Constructing wrapper function "driver.stellar_spectrum"...
              stellar_spectrum(mact,logt,lbol,logg,phase,ffco,wght,spec_out,[ns])
            Constructing wrapper function "driver.get_setup_vars"...
              cvms = get_setup_vars()
            Constructing wrapper function "driver.get_nz"...
              n_z = get_nz()
            Constructing wrapper function "driver.get_zlegend"...
              z_legend = get_zlegend(n_z)
            Constructing wrapper function "driver.get_timefull"...
              timefull = get_timefull(n_age)
            Constructing wrapper function "driver.get_ntfull"...
              n_age = get_ntfull()
            Constructing wrapper function "driver.get_nspec"...
              ns = get_nspec()
            Constructing wrapper function "driver.get_nbands"...
              nb = get_nbands()
            Constructing wrapper function "driver.get_lambda"...
              lambda = get_lambda(ns)
            Constructing wrapper function "driver.get_isochrone_dimensions"...
              n_age,n_mass = get_isochrone_dimensions()
            Constructing wrapper function "driver.get_nmass_isochrone"...
              nmass = get_nmass_isochrone(zz,tt)
            Constructing wrapper function "driver.get_stats"...
              age,mass_csp,lbol_csp,sfr,mdust = get_stats(n_age)
            Constructing wrapper function "driver.write_isoc"...
              write_isoc(outfile)
    Wrote C/API module "_fsps" to file "/var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/src.macosx-10.11-x86_64-2.7/_fspsmodule.c"
    Fortran 90 wrappers are saved to "/var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/src.macosx-10.11-x86_64-2.7/_fsps-f2pywrappers2.f90"
  adding '/var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/src.macosx-10.11-x86_64-2.7/fortranobject.c' to sources.
  adding '/var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/src.macosx-10.11-x86_64-2.7' to include_dirs.
copying /usr/local/lib/python2.7/site-packages/numpy/f2py/src/fortranobject.c -> /var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/src.macosx-10.11-x86_64-2.7
copying /usr/local/lib/python2.7/site-packages/numpy/f2py/src/fortranobject.h -> /var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/src.macosx-10.11-x86_64-2.7
  adding '/var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/src.macosx-10.11-x86_64-2.7/_fsps-f2pywrappers2.f90' to sources.
build_src: building npy-pkg config files
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize Gnu95FCompiler
Found executable /usr/local/bin/gfortran
Found executable /usr/local/bin/gcc-5
customize Gnu95FCompiler
customize Gnu95FCompiler using build_ext
building '_fsps' extension
compiling C sources
C compiler: /usr/local/bin/gcc-5 -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes

creating /var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/var
creating /var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/var/folders
creating /var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/var/folders/t2
creating /var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn
creating /var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T
creating /var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh
creating /var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/src.macosx-10.11-x86_64-2.7
compile options: '-I/Users/Nell/programs/fsps/src -I/var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/src.macosx-10.11-x86_64-2.7 -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c'
gcc-5: /var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/src.macosx-10.11-x86_64-2.7/_fspsmodule.c
In file included from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1761:0,
                 from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/src.macosx-10.11-x86_64-2.7/fortranobject.h:13,
                 from /var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/src.macosx-10.11-x86_64-2.7/_fspsmodule.c:18:
/usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
/var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/src.macosx-10.11-x86_64-2.7/_fspsmodule.c:144:12: warning: 'f2py_size' defined but not used [-Wunused-function]
 static int f2py_size(PyArrayObject\* var, ...)
            ^
gcc-5: /var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/src.macosx-10.11-x86_64-2.7/fortranobject.c
In file included from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1761:0,
                 from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/src.macosx-10.11-x86_64-2.7/fortranobject.h:13,
                 from /var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/src.macosx-10.11-x86_64-2.7/fortranobject.c:2:
/usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
compiling Fortran 90 module sources
Fortran f77 compiler: /usr/local/bin/gfortran -Wall -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops
Fortran f90 compiler: /usr/local/bin/gfortran -fPIC -fPIC -O3 -funroll-loops
Fortran fix compiler: /usr/local/bin/gfortran -Wall -ffixed-form -fno-second-underscore -fPIC -fPIC -O3 -funroll-loops
compile options: '-I/Users/Nell/programs/fsps/src -I/var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/src.macosx-10.11-x86_64-2.7 -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c'
extra options: '-J/var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/ -I/var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/'
gfortran:f90: fsps.f90
fsps.f90:144:17: Error: 'sf_slope' at (1) is not a member of the 'params' structure
fsps.f90:144:17: Error: 'sf_slope' at (1) is not a member of the 'params' structure
error: Command "/usr/local/bin/gfortran -fPIC -fPIC -O3 -funroll-loops -I/Users/Nell/programs/fsps/src -I/var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/src.macosx-10.11-x86_64-2.7 -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c -c fsps.f90 -o /var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/fsps.o -J/var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/ -I/var/folders/t2/rr3k4qm54xg2vq26yngyj7cw0000gn/T/tmpFFGdJh/" failed with exit status 1

**Comment by bd-j** [comment]
Oh no! What is your FSPS commit hash?  There was a change to FSPS over the summer, where sf_theta was renamed sf_slope.  The most recent FSPS/master is 6febb61.  Having the most recent fsps should fix the build for numpy 1.8.2.

I don't know what's wrong with the numpy 1.10 build.

**Comment by bd-j** [comment]
It looks like the numpy 1.10 build is having issues with wrapping the FSPS params structure.  This kind of error pops up on the numpy issues list, where it is suggested that Fortran structures aren't supported at all in f2py!  e.g. numpy/numpy#4645  any thoughts @dfm?

Also, I've been able to build python-FSPS with numpy 1.9.2, I think from homebrew

**Comment by nell-byler** [comment]
YES! working now -- I had tried the most recent git FSPS with numpy 1.10, and 1.8 and the older FSPS with numpy 1.10 and 1.8, but only tried the older version with 1.9.2 -- I still get f2py errors but python-fsps installs and runs which is all I care about right now ^__^ yay!

**Comment by Nolaa** [comment]
I have Numpy and SPS installed and have added the "SPS_HOME" as an environment variable to  .bash_profile like this:
```
export SPS_HOME="/Users/najmeh/Research/Autumn2015/FSPSmodel-Charley_Coonroy/fsps-master"
```
Then I edited the makefile in the src directory. 
But, when I try to install fsps using this command:
```
pip install fsps
```
I keep getting this error:
```
Collecting fsps
  Using cached fsps-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-I1078Y/fsps/setup.py", line 75, in <module>
        from fsps import __version__
      File "fsps/__init__.py", line 30, in <module>
        raise ImportError("You need to have the SPS_HOME environment variable")
    ImportError: You need to have the SPS_HOME environment variable
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-I1078Y/fsps
```

I have no idea how to fix it. Any help on that will be appreciated.

**Comment by bd-j** [comment]
Hi @Nolaa.  The package version installed by pip is unfortunately quite out of date and does not work with the most recent versions of FSPS, sorry about that.  Please follow the "Installing development version" instructions at  http://dan.iel.fm/python-fsps/current/installation.

Also, make sure you compile FSPS (following the instructions in the FSPS manual) *before* installing python-fsps.  If you are still having problems with the SPS_HOME variable, try typing ```echo $SPS_HOME``` at the command line to make sure the variable is properly set.

**Comment by Nolaa** [comment]
Thanks for your comment @bd-j . This time I get another error about fsps 
```
bash-3.2$ echo $SPS_HOME
/Users/najmeh/Research/Autumn2015/FSPSmodel-Charley_Coonroy/fsps-master
bash-3.2$ git clone https://github.com/dfm/python-fsps.git
Cloning into 'python-fsps'...
remote: Counting objects: 850, done.
remote: Total 850 (delta 0), reused 0 (delta 0), pack-reused 850
Receiving objects: 100% (850/850), 365.82 KiB | 0 bytes/s, done.
Resolving deltas: 100% (451/451), done.
Checking connectivity... done.
bash-3.2$ cd python-fsps
bash-3.2$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 87, in <module>
    from fsps import __version__
  File "/Users/najmeh/python-fsps/fsps/__init__.py", line 41, in <module>
    raise ImportError("Your FSPS version is not under git version "
ImportError: Your FSPS version is not under git version control. FSPS is now available on github at https://github.com/cconroy20/fsps
bash-3.2$ 
```

**Comment by bd-j** [comment]
@Nolaa,  it looks like there is something wrong with your FSPS installation, or it is a very old version.

If you want to do a clean install of FSPS, you can do the following
```
cd ~
git clone https://github.com/cconroy20/fsps.git
export SPS_HOME="$HOME/fsps"
cd fsps/src
make clean
make all
./simple.exe
```
where the last line is to check that FSPS is properly installed - it should not result in any errors.  You should also add the export SPS_HOME line to your bash_profile, as you've done before.

Then you should be able to do
```
cd ~
git clone https://github.com/dfm/python-fsps.git
cd python-fsps
python setup.py install
```
without any errors.

Hope this helps.

**Comment by Nolaa** [comment]
Thank you very much @bd-j . It did work, the only thing is every time i open a new terminal, I need to type ``` export SPS_HOME="$HOME/fsps"``` before running python.

**Comment by bd-j** [comment]
glad that worked, you might have to add the ```export SPS_HOME="$HOME/fsps"``` to ```.bashrc``` instead of ```.bash_profile``` to have it set all the time.

**Comment by Nolaa** [comment]
I did this before. What I just figured out is that I need to change my default login shell to bash instead of typing ```bash``` ( to change the shell ) and then ```export SPS_HOME="$HOME/fsps"``` in .bashrc every time I open a new terminal. Now it is running.

**Comment by dr-guangtou** [comment]
Hi, Any updates on the numpy 1.10.1 build?  

I blindly updated numpy to 1.10.1 too, and python-fsps failed the installation....Do I need to go back to Numpy 1.9 for now?

**Comment by bd-j** [comment]
I haven't had time to build the numpy development version from source to make the check and write up an issue for numpy if it *doesn't* work.  For now yes, v1.9.3 should work if you can get back to it.

**Comment by bd-j** [comment]
see #49, this appears to be solved in numpy v1.11

**Comment by bd-j** [comment]
It looks like numpy have backported the f2py fixes from 1.11 to at least 1.10.4, such that python-fsps succesfully compiles using the latest macports numpy version (which is 1.10.4).   @nell-byler hope this helps.

**Comment by bd-j** [comment]
Closing as the problems with numpy are gone in recent numpy versions.
